// <auto-generated />
using System;
using Coelsa.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Coelsa.Infrastructure.Persistence.Migraciones
{
    [DbContext(typeof(CoelsaDbContext))]
    [Migration("20260907170457_D2_MotivoRepudio")]
    partial class D2_MotivoRepudio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Coelsa.Domain.Entidades.Cesion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CuitCedente")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("CuitCesionario")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("DomicilioCesionario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("EcheqId")
                        .HasColumnType("uuid");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EcheqId", "Numero")
                        .IsUnique()
                        .HasDatabaseName("ix_cesiones_echeq_numero_unicos");

                    b.ToTable("cesiones", (string)null);
                });

            modelBuilder.Entity("Coelsa.Domain.Entidades.ChequeFisico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Cmc7")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CuitBeneficiario")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("CuitLibrador")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("FechaDiferimiento")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaEmision")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<int>("Moneda")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("MotivoRechazo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Cmc7")
                        .IsUnique();

                    b.HasIndex("CuitBeneficiario", "FechaCreacion")
                        .HasDatabaseName("ix_cheques_cuit_beneficiario_activos")
                        .HasFilter("\"Activo\" = true");

                    b.HasIndex("CuitLibrador", "FechaCreacion")
                        .HasDatabaseName("ix_cheques_cuit_librador_activos")
                        .HasFilter("\"Activo\" = true");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("CuitLibrador", "FechaCreacion"), new[] { "Cmc7", "CuitBeneficiario", "Monto", "Moneda", "FechaEmision", "FechaDiferimiento", "FechaVencimiento", "Estado", "MotivoRechazo" });

                    b.ToTable("cheques_fisicos", (string)null);
                });

            modelBuilder.Entity("Coelsa.Domain.Entidades.Chequera", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CuentaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaHabilitacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<int>("ProximoNumero")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CuentaId", "Numero")
                        .IsUnique();

                    b.HasIndex("CuentaId", "Estado", "ProximoNumero")
                        .HasDatabaseName("ix_chequeras_cuenta_con_lugar");

                    b.ToTable("chequeras", (string)null);
                });

            modelBuilder.Entity("Coelsa.Domain.Entidades.Cuenta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("Cbu")
                        .IsRequired()
                        .HasMaxLength(22)
                        .HasColumnType("character varying(22)");

                    b.Property<string>("CuitTitular")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Moneda")
                        .HasColumnType("integer");

                    b.Property<string>("NombreTitular")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Cbu")
                        .IsUnique();

                    b.HasIndex("CuitTitular", "Activa")
                        .HasDatabaseName("ix_cuentas_cuit_titular");

                    b.ToTable("cuentas", (string)null);
                });

            modelBuilder.Entity("Coelsa.Domain.Entidades.Devolucion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CuitSolicitante")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<Guid>("EcheqId")
                        .HasColumnType("uuid");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Motivo")
                        .HasMaxLength(280)
                        .HasColumnType("character varying(280)");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EcheqId", "Numero")
                        .IsUnique()
                        .HasDatabaseName("ix_devoluciones_echeq_numero_unicos");

                    b.ToTable("devoluciones", (string)null);
                });

            modelBuilder.Entity("Coelsa.Domain.Entidades.Echeq", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("CantidadEndosos")
                        .HasColumnType("integer");

                    b.Property<int>("Caracter")
                        .HasColumnType("integer");

                    b.Property<string>("CbuEmisor")
                        .IsRequired()
                        .HasMaxLength(22)
                        .HasColumnType("character varying(22)");

                    b.Property<string>("Cmc7")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Concepto")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("CuitBeneficiario")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("CuitLibrador")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("EmailNotificacion")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("FechaDiferimiento")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaEmision")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<string>("IdEcheq")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<int>("Moneda")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Motivo")
                        .HasMaxLength(280)
                        .HasColumnType("character varying(280)");

                    b.Property<int?>("MotivoRechazo")
                        .HasColumnType("integer");

                    b.Property<string>("MotivoRepudio")
                        .HasMaxLength(280)
                        .HasColumnType("character varying(280)");

                    b.Property<string>("NombreBeneficiario")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NombreLibrador")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("NumeroCheque")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroChequera")
                        .HasColumnType("integer");

                    b.Property<string>("Referencia")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("TipoDocBeneficiario")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Cmc7")
                        .IsUnique();

                    b.HasIndex("IdEcheq")
                        .IsUnique();

                    b.HasIndex("CuitBeneficiario", "FechaCreacion")
                        .HasDatabaseName("ix_echeqs_cuit_beneficiario_activos")
                        .HasFilter("\"Activo\" = true");

                    b.HasIndex("CuitLibrador", "FechaCreacion")
                        .HasDatabaseName("ix_echeqs_cuit_librador_activos")
                        .HasFilter("\"Activo\" = true");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("CuitLibrador", "FechaCreacion"), new[] { "IdEcheq", "CuitBeneficiario", "Monto", "Moneda", "FechaEmision", "FechaDiferimiento", "FechaVencimiento", "Estado", "MotivoRechazo" });

                    b.HasIndex("CbuEmisor", "NumeroChequera", "NumeroCheque")
                        .IsUnique()
                        .HasDatabaseName("ix_echeqs_cbu_chequera_numero");

                    b.ToTable("echeqs", (string)null);
                });

            modelBuilder.Entity("Coelsa.Domain.Entidades.Endoso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CuitEndosante")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("CuitEndosatario")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<Guid>("EcheqId")
                        .HasColumnType("uuid");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EcheqId", "Orden")
                        .IsUnique()
                        .HasDatabaseName("ix_endosos_echeq_orden_unicos");

                    b.ToTable("endosos", (string)null);
                });

            modelBuilder.Entity("Coelsa.Infrastructure.Persistence.EntradaIdempotencia", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("BodyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Key");

                    b.ToTable("idempotency_keys", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
