// <auto-generated />
using System;
using Coelsa.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Coelsa.Infrastructure.Persistence.Migraciones
{
    [DbContext(typeof(CoelsaDbContext))]
    [Migration("20260906021429_EcheqSinBancoCuenta")]
    partial class EcheqSinBancoCuenta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Coelsa.Domain.Entidades.ChequeFisico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Cmc7")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CuitBeneficiario")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("CuitLibrador")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("FechaDiferimiento")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaEmision")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Moneda")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("MotivoRechazo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Cmc7")
                        .IsUnique();

                    b.HasIndex("CuitBeneficiario", "FechaCreacion")
                        .HasDatabaseName("ix_cheques_cuit_beneficiario_activos")
                        .HasFilter("\"Activo\" = true");

                    b.HasIndex("CuitLibrador", "FechaCreacion")
                        .HasDatabaseName("ix_cheques_cuit_librador_activos")
                        .HasFilter("\"Activo\" = true");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("CuitLibrador", "FechaCreacion"), new[] { "Cmc7", "CuitBeneficiario", "Monto", "Moneda", "FechaEmision", "FechaDiferimiento", "Estado", "MotivoRechazo" });

                    b.ToTable("cheques_fisicos", (string)null);
                });

            modelBuilder.Entity("Coelsa.Domain.Entidades.Echeq", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("CantidadEndosos")
                        .HasColumnType("integer");

                    b.Property<string>("Cmc7")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CuitBeneficiario")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("CuitLibrador")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("FechaDiferimiento")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaEmision")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdEcheq")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<int>("Moneda")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("MotivoRechazo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Cmc7")
                        .IsUnique();

                    b.HasIndex("IdEcheq")
                        .IsUnique();

                    b.HasIndex("CuitBeneficiario", "FechaCreacion")
                        .HasDatabaseName("ix_echeqs_cuit_beneficiario_activos")
                        .HasFilter("\"Activo\" = true");

                    b.HasIndex("CuitLibrador", "FechaCreacion")
                        .HasDatabaseName("ix_echeqs_cuit_librador_activos")
                        .HasFilter("\"Activo\" = true");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("CuitLibrador", "FechaCreacion"), new[] { "IdEcheq", "CuitBeneficiario", "Monto", "Moneda", "FechaEmision", "FechaDiferimiento", "Estado", "MotivoRechazo" });

                    b.ToTable("echeqs", (string)null);
                });

            modelBuilder.Entity("Coelsa.Infrastructure.Persistence.EntradaIdempotencia", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("BodyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Key");

                    b.ToTable("idempotency_keys", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
